# Generated by Django 4.0.2 on 2022-02-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_csv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_csv',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='data_json',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
